name: Release

on:
  release:
    types: created

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@master
      - name: Build poppler
        run: make distribution
      - name: Upload the artifacts
        uses: actions/upload-artifact@v1
        with:
          name: poppler
          path: export/poppler.zip
      - name: Publish the artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: export/poppler.zip
          asset_name: poppler.zip
          asset_content_type: application/zip
